version: '3'
services:
    course-service:
        build: ./course-service
        # volumes update server realtime, update vao container chu ko update vao image
        volumes: 
            - ./course-service:/usr/src/app
        ports: 
            - 5001:8080
    website:
        image: nginx:alpine
        # volumes giup bind 2 folder voi nhau, /usr/share/nginx/html la folder ma image nginx nay recommend minh su dung
        volumes:
            - ./website:/usr/share/nginx/html
        ports:
            - 5002:80
        depends_on:
            - course-service